name: Create VM
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the Instance' 
        required: true 
      cpus:
        description: 'cpus for the instance'
        required: true
      memory:
        description: 'Memory Gbs'
        required: true
      os_template:
        description: 'os tmeplate for vm'
        required: True
      actions:
        description: 'Action to perform (create/delete)'
        required: true
# Jobs to be executed in this workflow
jobs:
  # Job for create instance
  create_vm:
    runs-on: ubuntu-latest
    # Execute this step only if the action input is "create"
    if: ${{ github.event.inputs.actions == 'create' }}
  
    steps:
    
    # checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Echo test
      run: echo ${{ github.event.inputs.name }}

    - name: Set up kubectl for Minikube
      run: |
        sudo apt-get update -q
        sudo apt-get install -y kubectl
        kubectl version --client

        minikube config set driver docker
        minikube start
        kubectl cluster-info

    - name: Clone Config Repository
      run: |
        git clone https://github.com/shanti91/test-gha3.git config-repo

    - name: Show Contents of Config Repository
      run: |
        ls -R config-repo

    - name: Deploy from Config Repository
      run: |
        kubectl apply -f config-repo/virtualmachine.yaml
    
    


#------------------------------------------------------------------------------------
  # Update VM
  update_vm:
    runs-on: ubuntu-latest
    
    # Execute this job only if the action input is "update"
    if: ${{ github.event.inputs.action == 'update' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
