name: Create VM
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the Instance' 
        required: true 
      cpus:
        description: 'cpus for the instance'
        required: true
      memory:
        description: 'Memory Gbs'
        required: true
      os_template:
        description: 'os tmeplate for vm'
        required: True
      actions:
        description: 'Action to perform (create/delete)'
        required: true
# Jobs to be executed in this workflow
jobs:
  # Job for create instance
  create_vm:
    runs-on: ubuntu-latest
    # Execute this step only if the action input is "create"
    if: ${{ github.event.inputs.actions == 'create' }}
  
    steps:
    
    # checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Echo test
      run: echo ${{ github.event.inputs.name }}
    


#------------------------------------------------------------------------------------
  # Update VM
  update_vm:
    runs-on: ubuntu-latest
    
    # Execute this job only if the action input is "update"
    if: ${{ github.event.inputs.action == 'update' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
